version: "3"

# to use the keyword 'services' to start to create services
services:

  # First service (container): the server.
  server:
    # to execute the service
    build: server/

    # to execute "python ./server.py".
    command: python ./server.py

    # If we want to access the server from our computer (outside the container),
    # we must share the content port with our computer's port.
    ports:
      - 9090:9090

    network_mode: host

  # Second service (container): the client
  client:
    # to execute this service
    build: client/

    # The command to execute once the image is created.
    # The following command will execute "python ./client.py".
    command: python ./client.py

    # Here we define that the container can access to the 'localhost' of the computer.
    network_mode: host

    # Here, we want the 'client' service to wait until the 'server' service is ready.
    depends_on:
      - server